run tests:
  stage: test
  image: python:latest
  script:
    - pip install coverage
    - coverage run -m unittest discover tests "*_test.py"
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
